% Run this function first to extra functions to path
function [current_dir] = addPaths()
    current_dir =  fileparts(which('addPaths.m'));      
    addpath(current_dir,...
        [current_dir filesep 'snowp_function'], ...
        [current_dir filesep 'snowp_data'], ...
        [current_dir filesep 'snowp_figure'], ...
        [current_dir filesep 'snowp_mfile']);
end